[project]
name = "fapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "lightgbm>=4.6.0",
    "numpy>=2.3.3",
    "onnx>=1.19.1",
    "scikit-learn>=1.7.2",
    "torch>=2.8.0",
]
